name: Release Action
on:
  workflow_dispatch:
    inputs:
      bump-level:
        type: choice
        options: [patch, minor, major]
        required: true
        description: Bump to patch or minor or major
defaults:
  run:
    shell: bash
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - env:
          USERNAME: github-actions[bot]
          EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          BUMP_LEVEL: ${{ inputs.bump-level }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "${USERNAME}"
          git config --global user.email "${USERNAME}"
          version="$(.github/scripts/bump.sh "${BUMP_LEVEL}")"
          gh release create "${version}" --title "${version}" --generate-notes
