name: Test Action
on: pull_request
defaults:
  run:
    shell: bash
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v5
      - name: Setup
        run: date > foo.md
      - name: Exercise
        id: exercise
        uses: ./
        with:
          message: Test
      - name: Verify
        run: |
          set -x
          test "$(gh pr view "${BRANCH}" --json title --jq .title)" = "Test"
        env:
          BRANCH: ${{ steps.exercise.outputs.branch }}
      - name: Teardown
        if: ${{ always() }}
        run: |
          gh pr close "${BRANCH}" || true
          git push origin "${BRANCH}" --delete || true
        env:
          BRANCH: ${{ steps.exercise.outputs.branch }}
